name       : fontcustom
version    : 2.0.0
release    : 1
source     :
    - https://rubygems.org/downloads/fontcustom-2.0.0.gem : c6da0f8d0b789acb33ae39059fea321b2198b45828e9f9b61ecbc9db53b92be5
license    : MIT
component  : multimedia.graphics
summary    : Generate custom icon webfonts from the comfort of the command line.
description: |
    Generate custom icon webfonts from the comfort of the command line.
extract    : no
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - fontforge
    - sfnt2woff-zopfli
    - woff2
    - woff-tools
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/fontcustom-$version.gem
